"""Exact real-space reduction for Cartesian axis-reflection symmetries.

PARSEC discovers a point group, stores only an irreducible real-space wedge,
and solves each Abelian representation on that wedge.  The complete point-
group machinery is larger than the acceleration needed by the Poisson solve,
whose source and solution transform as the totally symmetric representation.

This module implements the rigorously checkable subset generated by
``(x, y, z) -> (+/-x, +/-y, +/-z)``.  A transformation is accepted only when
it maps the atom list species-by-species and maps every active lattice point
onto another active point.  The resulting normalized expansion ``U`` obeys

``U.T @ U = I`` and ``A_wedge = U.T @ A_full @ U``.

The normalization handles grid points on a reflection plane, so the code is
valid for both PARSEC's half-grid shift and zero-shift diagnostic grids.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations, permutations, product
from typing import Sequence

import numpy as np
import scipy.sparse as sp

from parsec_python.Grid import RealSpaceGrid
from parsec_python.models import Atom


def _has_tolerance_perfect_matching(
    transformed: np.ndarray,
    candidates: np.ndarray,
    tolerance: float,
) -> bool:
    """Test exact one-to-one atom matching on a distance-threshold graph.

    Symmetry needs a feasible bijection whose *every* edge is within the atom
    tolerance.  A minimum-total-distance Hungarian solve is more machinery
    than this Boolean condition requires and can theoretically reject a
    feasible threshold matching when another assignment has a smaller total
    but one edge just outside the threshold.  Deterministic augmenting paths
    solve the intended bipartite feasibility problem directly.  Species
    groups in finite systems are small, so the cubic worst case is negligible
    and avoids importing the large ``scipy.optimize`` package at startup.
    """

    transformed = np.asarray(transformed, dtype=np.float64)
    candidates = np.asarray(candidates, dtype=np.float64)
    if transformed.shape != candidates.shape or (
        transformed.ndim != 2 or transformed.shape[1] != 3
    ):
        return False
    count = int(transformed.shape[0])
    if count == 0:
        return True
    distances = np.linalg.norm(
        transformed[:, None, :] - candidates[None, :, :], axis=2
    )
    adjacency = [
        np.flatnonzero(distances[row] <= tolerance).tolist()
        for row in range(count)
    ]
    if any(not columns for columns in adjacency):
        return False

    matched_row = np.full(count, -1, dtype=np.int64)

    def augment(row: int, visited: np.ndarray) -> bool:
        for column in adjacency[row]:
            if visited[column]:
                continue
            visited[column] = True
            previous = int(matched_row[column])
            if previous < 0 or augment(previous, visited):
                matched_row[column] = row
                return True
        return False

    # Constrained rows first reduces unsuccessful augmenting-path searches;
    # stable ordering keeps symmetry detection deterministic.
    row_order = sorted(range(count), key=lambda row: len(adjacency[row]))
    for row in row_order:
        if not augment(row, np.zeros(count, dtype=bool)):
            return False
    return True


def _atoms_are_invariant(
    atoms: Sequence[Atom], signs: np.ndarray, tolerance: float
) -> bool:
    """Return whether one diagonal sign operation preserves labeled atoms."""

    by_species: dict[str, np.ndarray] = {}
    for symbol in {atom.symbol for atom in atoms}:
        by_species[symbol] = np.asarray(
            [atom.position for atom in atoms if atom.symbol == symbol],
            dtype=np.float64,
        )
    for symbol, candidates in by_species.items():
        transformed = np.asarray(
            [
                signs * np.asarray(atom.position, dtype=np.float64)
                for atom in atoms
                if atom.symbol == symbol
            ]
        )
        if not _has_tolerance_perfect_matching(
            transformed, candidates, tolerance
        ):
            return False
    return True


def _grid_row_mapping(
    grid: RealSpaceGrid,
    signs: np.ndarray,
    lattice_tolerance: float,
) -> np.ndarray | None:
    """Map all rows under one sign operation, or reject the operation."""

    operation = np.diag(np.asarray(signs, dtype=np.int8))
    parameters = _integer_signed_permutation_parameters(
        grid, operation, lattice_tolerance
    )
    if parameters is None:
        return None
    sources, factors, offset = parameters
    transformed = (
        grid.integer_coordinates[:, sources] * factors + offset
    )
    rows = grid.rows_for_integer_coordinates(transformed)
    if np.any(rows < 0):
        return None
    return rows


def _integer_signed_permutation_parameters(
    grid: RealSpaceGrid,
    operation: np.ndarray,
    lattice_tolerance: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray] | None:
    """Return the exact integer permutation/sign/offset lattice action.

    For a signed permutation ``R`` and shifted lattice coordinate ``n+s``,

    ``R(n+s)-s = signs*n[sources] + (R*s-s)``.

    The last term must be integer for the operation to preserve the lattice.
    Computing that three-value condition once avoids a grid-sized float64
    matrix multiply and rounding pass for every symmetry operation.
    """

    matrix = np.asarray(operation, dtype=np.int8)
    if matrix.shape != (3, 3):
        return None
    absolute = np.abs(matrix)
    if not np.all(np.sum(absolute, axis=0) == 1) or not np.all(
        np.sum(absolute, axis=1) == 1
    ):
        return None
    sources = np.argmax(absolute, axis=1)
    factors = matrix[np.arange(3), sources].astype(np.int64, copy=False)
    shift = np.asarray(grid.settings.shift, dtype=np.float64)
    floating_offset = shift @ matrix.T - shift
    offset = np.rint(floating_offset).astype(np.int64)
    if (
        np.max(np.abs(floating_offset - offset), initial=0.0)
        > lattice_tolerance
    ):
        return None
    return sources, factors, offset


def _atoms_are_invariant_operation(
    atoms: Sequence[Atom], operation: np.ndarray, tolerance: float
) -> bool:
    """Return whether an orthogonal signed permutation preserves the atoms."""

    by_species: dict[str, np.ndarray] = {}
    for symbol in {atom.symbol for atom in atoms}:
        by_species[symbol] = np.asarray(
            [atom.position for atom in atoms if atom.symbol == symbol],
            dtype=np.float64,
        )
    matrix = np.asarray(operation, dtype=np.float64)
    for candidates in by_species.values():
        transformed = candidates @ matrix.T
        if not _has_tolerance_perfect_matching(
            transformed, candidates, tolerance
        ):
            return False
    return True


def _grid_row_mapping_operation(
    grid: RealSpaceGrid,
    operation: np.ndarray,
    lattice_tolerance: float,
) -> np.ndarray | None:
    """Map rows under one signed permutation, using exact lattice rounding."""

    parameters = _integer_signed_permutation_parameters(
        grid, operation, lattice_tolerance
    )
    if parameters is None:
        return None
    sources, factors, offset = parameters
    transformed = (
        grid.integer_coordinates[:, sources] * factors + offset
    )
    rows = grid.rows_for_integer_coordinates(transformed)
    return None if np.any(rows < 0) else rows


def _signed_permutation_operations() -> tuple[np.ndarray, ...]:
    """Return all 48 exact Cartesian signed-permutation matrices."""

    operations: list[np.ndarray] = []
    for permutation in permutations(range(3)):
        for signs in product((-1, 1), repeat=3):
            matrix = np.zeros((3, 3), dtype=np.int8)
            for row, column in enumerate(permutation):
                matrix[row, column] = signs[row]
            operations.append(matrix)
    return tuple(operations)


@dataclass(frozen=True)
class AxisReflectionReduction:
    """Normalized orbit map for an accepted Cartesian reflection subgroup.

    ``full_to_wedge[i]`` identifies the orbit containing full-grid row ``i``.
    ``representative_rows`` contains one real row per orbit.  If orbit ``w``
    has multiplicity ``m_w``, the normalized totally symmetric expansion is

    ``x_full[i] = x_wedge[w] / sqrt(m_w)``.
    """

    signs: np.ndarray
    representative_rows: np.ndarray
    full_to_wedge: np.ndarray
    multiplicities: np.ndarray

    @property
    def group_order(self) -> int:
        return int(self.signs.shape[0])

    @property
    def full_size(self) -> int:
        return int(self.full_to_wedge.size)

    @property
    def wedge_size(self) -> int:
        return int(self.representative_rows.size)

    @property
    def reduction_ratio(self) -> float:
        return self.full_size / self.wedge_size

    @classmethod
    def detect(
        cls,
        grid: RealSpaceGrid,
        atoms: Sequence[Atom],
        *,
        atom_tolerance: float = 1.0e-7,
        lattice_tolerance: float = 1.0e-10,
    ) -> "AxisReflectionReduction":
        """Detect the largest valid diagonal-sign subgroup.

        Identity is always retained.  The operations that preserve a finite
        labeled atom set form a group; intersecting them with exact grid
        automorphisms remains a group.  No approximate grid mapping is used.
        """

        if not atoms:
            raise ValueError("axis-reflection detection requires at least one atom")
        valid_signs: list[np.ndarray] = []
        mappings: list[np.ndarray] = []
        for values in product((-1, 1), repeat=3):
            signs = np.asarray(values, dtype=np.int8)
            if not _atoms_are_invariant(atoms, signs, atom_tolerance):
                continue
            mapping = _grid_row_mapping(grid, signs, lattice_tolerance)
            if mapping is None:
                continue
            valid_signs.append(signs)
            mappings.append(mapping)

        if not mappings:
            # This can only happen for an invalid grid because identity maps
            # both atoms and lattice exactly, but keep the failure explicit.
            raise ValueError("the identity operation did not preserve the active grid")

        # The minimum row in each orbit is a deterministic representative.
        canonical_rows = np.minimum.reduce(mappings)
        representative_rows = np.unique(canonical_rows)
        full_to_wedge = np.searchsorted(representative_rows, canonical_rows)
        multiplicities = np.bincount(
            full_to_wedge, minlength=representative_rows.size
        ).astype(np.int64, copy=False)
        if np.any(multiplicities <= 0):
            raise RuntimeError("invalid empty symmetry orbit")

        return cls(
            signs=np.ascontiguousarray(np.vstack(valid_signs), dtype=np.int8),
            representative_rows=np.ascontiguousarray(
                representative_rows, dtype=np.int64
            ),
            full_to_wedge=np.ascontiguousarray(full_to_wedge, dtype=np.int64),
            multiplicities=np.ascontiguousarray(multiplicities, dtype=np.int64),
        )

    def reduce_vector(self, values: np.ndarray) -> np.ndarray:
        """Apply ``U.T`` to a full vector, averaging symmetry noise exactly."""

        array = np.asarray(values, dtype=np.float64)
        if array.shape != (self.full_size,):
            raise ValueError("full vector does not match the symmetry map")
        sums = np.bincount(
            self.full_to_wedge,
            weights=array,
            minlength=self.wedge_size,
        )
        return sums / np.sqrt(self.multiplicities)

    def expand_vector(self, values: np.ndarray) -> np.ndarray:
        """Apply ``U`` to normalized totally symmetric wedge coordinates."""

        array = np.asarray(values, dtype=np.float64)
        if array.shape != (self.wedge_size,):
            raise ValueError("wedge vector does not match the symmetry map")
        scale = np.sqrt(self.multiplicities[self.full_to_wedge])
        return np.ascontiguousarray(array[self.full_to_wedge] / scale)

    def project_invariant(self, values: np.ndarray) -> np.ndarray:
        """Return ``U @ U.T @ values``, the orbit-wise average."""

        return self.expand_vector(self.reduce_vector(values))

    def reduce_operator(self, operator: sp.spmatrix) -> sp.csr_matrix:
        """Construct ``U.T @ operator @ U`` without materializing ``U``.

        For an invariant operator, all rows in one orbit are symmetry images.
        Selecting one representative gives ``R A E``.  Left/right orbit
        normalization converts that matrix to the orthonormal projection

        ``A_wv = sqrt(m_w/m_v) * (R A E)_wv``.
        """

        matrix = sp.csr_matrix(operator, dtype=np.float64)
        if matrix.shape != (self.full_size, self.full_size):
            raise ValueError("operator does not match the symmetry map")
        matrix.sum_duplicates()
        matrix.sort_indices()

        selected = matrix[self.representative_rows, :].tocoo(copy=False)
        wedge_columns = self.full_to_wedge[selected.col]
        unnormalized = sp.coo_matrix(
            (selected.data, (selected.row, wedge_columns)),
            shape=(self.wedge_size, self.wedge_size),
        ).tocsr()
        unnormalized.sum_duplicates()

        coo = unnormalized.tocoo(copy=False)
        roots = np.sqrt(self.multiplicities.astype(np.float64))
        data = coo.data * roots[coo.row] / roots[coo.col]
        reduced = sp.coo_matrix(
            (data, (coo.row, coo.col)), shape=unnormalized.shape
        ).tocsr()
        reduced.sum_duplicates()
        reduced.sort_indices()

        asymmetry = reduced - reduced.T
        maximum_asymmetry = (
            float(np.max(np.abs(asymmetry.data))) if asymmetry.nnz else 0.0
        )
        scale = float(np.max(np.abs(reduced.data), initial=1.0))
        if maximum_asymmetry > 5.0e-13 * scale:
            raise ValueError(
                "operator is not invariant under the detected reflections: "
                f"maximum reduced asymmetry is {maximum_asymmetry:.3e}"
            )
        return reduced


@dataclass(frozen=True)
class SignedPermutationReduction(AxisReflectionReduction):
    """Exact orbit map for a commuting signed-permutation involution group.

    ``generator_bits[g]`` gives the C2 generator exponents of operation ``g``.
    The group is therefore Abelian with complete real one-dimensional
    characters, while supporting mirror planes and twofold axes not aligned
    with the Cartesian coordinate axes.
    """

    operations: np.ndarray
    generator_bits: np.ndarray

    @classmethod
    def detect(
        cls,
        grid: RealSpaceGrid,
        atoms: Sequence[Atom],
        *,
        atom_tolerance: float = 1.0e-7,
        lattice_tolerance: float = 1.0e-10,
    ) -> AxisReflectionReduction:
        """Select the largest exact C2^k signed-permutation subgroup.

        The established diagonal-reflection result wins every tie.  Existing
        calculations therefore retain their representation order and random
        streams; a broader operation is adopted only when it strictly grows
        the usable exact group.
        """

        axis = AxisReflectionReduction.detect(
            grid,
            atoms,
            atom_tolerance=atom_tolerance,
            lattice_tolerance=lattice_tolerance,
        )
        valid: dict[bytes, tuple[np.ndarray, np.ndarray]] = {}
        identity = np.eye(3, dtype=np.int8)
        for operation in _signed_permutation_operations():
            if not np.array_equal(operation @ operation, identity):
                continue
            if not _atoms_are_invariant_operation(
                atoms, operation, atom_tolerance
            ):
                continue
            mapping = _grid_row_mapping_operation(
                grid, operation, lattice_tolerance
            )
            if mapping is not None:
                valid[operation.tobytes()] = (operation, mapping)

        candidates = [
            item[0]
            for key, item in sorted(
                valid.items(), key=lambda pair: pair[0]
            )
            if not np.array_equal(item[0], identity)
        ]
        best: tuple[list[np.ndarray], np.ndarray] | None = None
        # An elementary Abelian subgroup of O(3) has rank at most three.
        for rank in range(3, 0, -1):
            for generators in combinations(candidates, rank):
                if any(
                    not np.array_equal(left @ right, right @ left)
                    for left, right in combinations(generators, 2)
                ):
                    continue
                operations: list[np.ndarray] = []
                bits: list[tuple[int, ...]] = []
                seen: set[bytes] = set()
                usable = True
                for exponents in product((0, 1), repeat=rank):
                    operation = identity.copy()
                    for enabled, generator in zip(exponents, generators):
                        if enabled:
                            operation = operation @ generator
                    key = operation.astype(np.int8, copy=False).tobytes()
                    if key in seen or key not in valid:
                        usable = False
                        break
                    seen.add(key)
                    operations.append(valid[key][0])
                    bits.append(exponents)
                if usable and len(operations) > axis.group_order:
                    best = (
                        operations,
                        np.asarray(bits, dtype=np.int8),
                    )
                    break
            if best is not None:
                break
        if best is None:
            return axis

        operations, generator_bits = best
        mappings = [valid[operation.tobytes()][1] for operation in operations]
        canonical_rows = np.minimum.reduce(mappings)
        representative_rows = np.unique(canonical_rows)
        full_to_wedge = np.searchsorted(representative_rows, canonical_rows)
        multiplicities = np.bincount(
            full_to_wedge, minlength=representative_rows.size
        ).astype(np.int64, copy=False)
        return cls(
            # Retained solely for inherited group-order compatibility.  The
            # generalized representation builder uses operations/bits below.
            signs=np.ones((len(operations), 3), dtype=np.int8),
            representative_rows=np.ascontiguousarray(
                representative_rows, dtype=np.int64
            ),
            full_to_wedge=np.ascontiguousarray(full_to_wedge, dtype=np.int64),
            multiplicities=np.ascontiguousarray(multiplicities, dtype=np.int64),
            operations=np.ascontiguousarray(operations, dtype=np.int8),
            generator_bits=np.ascontiguousarray(generator_bits, dtype=np.int8),
        )


__all__ = [
    "AxisReflectionReduction",
    "SignedPermutationReduction",
    "_grid_row_mapping_operation",
]
