"""PARSEC-style selective two-pass Gram--Schmidt on CuPy arrays."""

from __future__ import annotations

from dataclasses import dataclass
import os
from typing import Any

import numpy as np

from ..backends.cupy import require_cupy
from ..backends.cupy_orthogonalize import subtract_active_prefix


_EPS = 2.22044605e-16
_EPS_BIG = 2.221e-16
_FIRST_REORTHOGONALIZATION_RATIO = 0.1
_SECOND_REORTHOGONALIZATION_RATIO = 0.68
_DEFAULT_QR_WORK_THRESHOLD = 100_000_000


@dataclass(frozen=True)
class DeviceOrthonormalizationResult:
    """Device basis plus dependent-vector recovery counts."""

    basis: Any
    random_replacements: int
    zero_replacements: int
    algorithm: str = "parsec_selective_mgs"


def _host_replacement(row_count: int, rng: Any) -> np.ndarray:
    """Draw from the caller's host stream before one explicit upload."""

    values = rng.uniform(-1.0, 1.0, row_count)
    return np.asarray(values, dtype=np.float64)


def _orthonormalize_literal(
    vectors: Any,
    *,
    existing_columns: int = 0,
    existing_are_orthonormal: bool = True,
    rng: Any | None = None,
    max_replacements: int = 100,
    copy: bool = True,
) -> DeviceOrthonormalizationResult:
    """Apply the literal sequential decisions from PARSEC ``orth_normal``.

    Norm values are deliberately transferred as scalars because the 0.1/0.68
    decisions are sequential algorithmic dependencies.  Large vectors,
    projections, and the complete basis remain on the GPU.  Replacement
    vectors are generated by the supplied host random stream; CHEBFF passes
    the same :class:`parsec_python.Eigensolvers.LapackRandom` instance that
    generated its initial trial basis.
    """

    cp, _ = require_cupy()
    array_stack = getattr(cp, "stack", np.stack)
    basis = cp.asarray(vectors, dtype=cp.float64)
    if basis.ndim != 2:
        raise ValueError("vectors must be a two-dimensional column matrix")
    row_count, column_count = map(int, basis.shape)
    if row_count < column_count:
        raise ValueError("cannot construct more orthonormal columns than rows")
    basis = basis.copy() if copy else basis

    existing_columns = int(existing_columns)
    if not 0 <= existing_columns <= column_count:
        raise ValueError("existing_columns is outside the basis")
    max_replacements = int(max_replacements)
    if max_replacements < 0:
        raise ValueError("max_replacements cannot be negative")
    generator = np.random.default_rng() if rng is None else rng

    first_column = existing_columns if existing_are_orthonormal else 0
    random_replacements = 0
    zero_replacements = 0

    for column in range(first_column, column_count):
        while True:
            vector = basis[:, column]
            # Queue the input norm before projection, but transfer it together
            # with the projected norm below.  PARSEC needs both values only
            # for the 0.1 acceptance decision, so the former per-column
            # ``input_norm.item()`` was an unnecessary CUDA synchronization.
            # The norm kernels and projection retain their original order and
            # arithmetic; only the two scalar downloads are coalesced.
            input_norm_device = cp.linalg.norm(vector)

            previous = basis[:, :column]
            if column:
                vector = vector - previous @ (previous.T @ vector)
            projected_norm_device = cp.linalg.norm(vector)
            norms = np.asarray(
                cp.asnumpy(
                    array_stack((input_norm_device, projected_norm_device))
                ),
                dtype=np.float64,
            )
            input_norm = float(norms[0])
            projected_norm = float(norms[1])

            if input_norm < _EPS_BIG:
                if random_replacements >= max_replacements:
                    raise np.linalg.LinAlgError(
                        "orthogonalization exceeded the replacement limit"
                    )
                basis[:, column] = cp.asarray(
                    _host_replacement(row_count, generator), dtype=cp.float64
                )
                random_replacements += 1
                zero_replacements += 1
                continue

            if projected_norm > _FIRST_REORTHOGONALIZATION_RATIO * input_norm:
                if abs(projected_norm - 1.0) >= _EPS:
                    vector = vector / projected_norm
                basis[:, column] = vector
                break

            once_projected_norm = projected_norm
            if column:
                vector = vector - previous @ (previous.T @ vector)
            projected_norm = float(cp.linalg.norm(vector).item())
            if (
                projected_norm
                > _SECOND_REORTHOGONALIZATION_RATIO * once_projected_norm
            ):
                if abs(projected_norm - 1.0) >= _EPS:
                    vector = vector / projected_norm
                basis[:, column] = vector
                break

            if random_replacements >= max_replacements:
                raise np.linalg.LinAlgError(
                    "orthogonalization exceeded the replacement limit"
                )
            basis[:, column] = cp.asarray(
                _host_replacement(row_count, generator), dtype=cp.float64
            )
            random_replacements += 1

    return DeviceOrthonormalizationResult(
        basis=basis,
        random_replacements=random_replacements,
        zero_replacements=zero_replacements,
    )


def _speculative_enabled(*, copy: bool) -> bool:
    value = os.environ.get("PARSEC_CUPY_SPECULATIVE_MGS", "complete")
    policy = value.strip().lower()
    if policy in {"0", "false", "no", "off"}:
        return False
    if policy in {"1", "true", "yes", "on", "complete"}:
        # CHEBDAV's copy=False appended blocks frequently require the second
        # PARSEC pass; speculating there repeats enough work to lose time.
        return bool(copy)
    if policy == "all":
        return True
    raise ValueError(
        "PARSEC_CUPY_SPECULATIVE_MGS must be complete, all, or off"
    )


def orthonormalize(
    vectors: Any,
    *,
    existing_columns: int = 0,
    existing_are_orthonormal: bool = True,
    rng: Any | None = None,
    max_replacements: int = 100,
    copy: bool = True,
) -> DeviceOrthonormalizationResult:
    """Apply PARSEC selective MGS with an audited device fast path.

    Well-conditioned filtered bases almost always accept PARSEC's first
    projection because ``||q'|| > 0.1 ||q||``.  Downloading both norms before
    every column nevertheless serializes the CUDA stream thousands of times.
    The fast path performs that common branch with device scalars, downloads
    all norm pairs once, and verifies every original decision afterward.

    If a zero/dependent vector or the 0.1 test would have selected PARSEC's
    second projection/replacement branch, the untouched input columns are
    restored and :func:`_orthonormalize_literal` is run.  Thus speculation
    changes synchronization only: accepted arithmetic and every exceptional
    decision retain the source algorithm.  Set
    ``PARSEC_CUPY_SPECULATIVE_MGS=off`` for a literal source-level trace, or
    ``all`` to speculate on CHEBDAV's appended blocks as well.  The default
    ``complete`` limits speculation to the measured-profitable complete
    CHEBFF/SUBSPACE bases.
    """

    if not _speculative_enabled(copy=copy):
        return _orthonormalize_literal(
            vectors,
            existing_columns=existing_columns,
            existing_are_orthonormal=existing_are_orthonormal,
            rng=rng,
            max_replacements=max_replacements,
            copy=copy,
        )

    cp, _ = require_cupy()
    array_where = getattr(cp, "where", np.where)
    array_abs = getattr(cp, "abs", np.abs)
    array_stack = getattr(cp, "stack", np.stack)
    source = cp.asarray(vectors, dtype=cp.float64)
    if source.ndim != 2:
        raise ValueError("vectors must be a two-dimensional column matrix")
    row_count, column_count = map(int, source.shape)
    if row_count < column_count:
        raise ValueError("cannot construct more orthonormal columns than rows")
    existing_columns = int(existing_columns)
    if not 0 <= existing_columns <= column_count:
        raise ValueError("existing_columns is outside the basis")
    max_replacements = int(max_replacements)
    if max_replacements < 0:
        raise ValueError("max_replacements cannot be negative")

    first_column = existing_columns if existing_are_orthonormal else 0
    basis = source.copy() if copy else source
    if first_column >= column_count:
        return DeviceOrthonormalizationResult(
            basis=basis,
            random_replacements=0,
            zero_replacements=0,
        )

    # copy=True already leaves source untouched.  CHEBDAV appends into a
    # shared allocation with copy=False, so preserve only the columns that
    # speculation may overwrite rather than duplicating its complete basis.
    original_appended = (
        None if copy else basis[:, first_column:column_count].copy()
    )
    audit_scalars = []
    for column in range(first_column, column_count):
        vector = basis[:, column]
        input_norm = cp.linalg.norm(vector)
        previous = basis[:, :column]
        if column:
            vector = vector - previous @ (previous.T @ vector)
        projected_norm = cp.linalg.norm(vector)
        # PARSEC skips division only for a norm within machine epsilon of one.
        # The positive guard prevents NaNs during failed speculation; failure
        # is detected below and rerun by the literal replacement-capable path.
        scale = array_where(
            (array_abs(projected_norm - 1.0) >= _EPS)
            & (projected_norm > 0.0),
            projected_norm,
            1.0,
        )
        basis[:, column] = vector / scale
        audit_scalars.extend((input_norm, projected_norm))

    audit = np.asarray(
        cp.asnumpy(array_stack(audit_scalars)), dtype=np.float64
    ).reshape(-1, 2)
    accepted = (
        np.all(np.isfinite(audit))
        and np.all(audit[:, 0] >= _EPS_BIG)
        and np.all(
            audit[:, 1]
            > _FIRST_REORTHOGONALIZATION_RATIO * audit[:, 0]
        )
    )
    if accepted:
        return DeviceOrthonormalizationResult(
            basis=basis,
            random_replacements=0,
            zero_replacements=0,
        )

    if not copy:
        assert original_appended is not None
        basis[:, first_column:column_count] = original_appended
        source = basis
    return _orthonormalize_literal(
        source,
        existing_columns=existing_columns,
        existing_are_orthonormal=existing_are_orthonormal,
        rng=rng,
        max_replacements=max_replacements,
        copy=copy,
    )


def chebdav_block_orth_requested(row_count: int, appended_columns: int) -> bool:
    """Select the audited block route only where it amortizes GPU setup."""

    policy = os.environ.get(
        "PARSEC_CUPY_CHEBDAV_BLOCK_ORTH", "auto"
    ).strip().lower()
    if policy not in {
        "auto", "on", "off", "1", "0", "true", "false", "yes", "no"
    }:
        raise ValueError(
            "PARSEC_CUPY_CHEBDAV_BLOCK_ORTH must be auto, on, or off"
        )
    if policy in {"on", "1", "true", "yes"}:
        return int(appended_columns) > 1
    if policy in {"off", "0", "false", "no"}:
        return False
    raw_rows = os.environ.get(
        "PARSEC_CUPY_CHEBDAV_BLOCK_ORTH_MIN_ROWS", "100000"
    ).strip()
    try:
        minimum_rows = int(raw_rows)
    except ValueError as error:
        raise ValueError(
            "PARSEC_CUPY_CHEBDAV_BLOCK_ORTH_MIN_ROWS must be an integer"
        ) from error
    if minimum_rows < 1:
        raise ValueError(
            "PARSEC_CUPY_CHEBDAV_BLOCK_ORTH_MIN_ROWS must be positive"
        )
    return int(row_count) >= minimum_rows and int(appended_columns) > 1


def orthonormalize_appended_block(
    vectors: Any,
    *,
    existing_columns: int,
    active_columns: int | None = None,
    rng: Any | None = None,
    max_replacements: int = 100,
) -> DeviceOrthonormalizationResult:
    """Orthogonalize a narrow appended block with GPU level-3 operations.

    If ``Q`` is the already orthonormal prefix and ``X`` the newly appended
    CHEBDAV block, two block projections form

    ``X <- X - Q(Q.T X)``.

    Two synchronization-free MGS passes then orthonormalize the six
    (normally) new columns.  This block-CGS2/MGS2 form is algebraically the
    same span construction as the source column-at-a-time selective
    Gram--Schmidt, but maps the expensive projection against the growing
    prefix to cuBLAS level-3 work.

    Rank and FP64 orthogonality are audited after device MGS2.  An unusual
    dependent block or failed audit retries with Householder QR; a second
    failure restores the untouched columns and enters the replacement-capable
    literal PARSEC routine.
    """

    cp, _ = require_cupy()
    basis = cp.asarray(vectors, dtype=cp.float64)
    if basis.ndim != 2:
        raise ValueError("vectors must be a two-dimensional column matrix")
    rows, workspace_columns = map(int, basis.shape)
    columns = (
        workspace_columns if active_columns is None else int(active_columns)
    )
    existing_columns = int(existing_columns)
    if not 0 <= existing_columns <= columns <= workspace_columns:
        raise ValueError("existing_columns is outside the basis")
    if rows < columns:
        raise ValueError("cannot construct more orthonormal columns than rows")
    if existing_columns == columns:
        return DeviceOrthonormalizationResult(
            basis, 0, 0, algorithm="block_cgs2_householder_qr"
        )

    appended = basis[:, existing_columns:columns]
    original = appended.copy()
    prefix = basis[:, :existing_columns]
    candidate = cp.asfortranarray(appended)
    full_workspace_projection = (
        os.environ.get(
            "PARSEC_CUPY_CHEBDAV_FULL_WORKSPACE_CGS", "1"
        ).strip().lower()
        not in {"0", "false", "no", "off"}
        and workspace_columns > columns
        and basis.flags.c_contiguous
    )
    fused_prefix_update = (
        full_workspace_projection
        and int(candidate.shape[1]) <= 6
        and os.environ.get(
            "PARSEC_CUPY_CHEBDAV_FUSED_PREFIX_UPDATE", "1"
        ).strip().lower()
        not in {"0", "false", "no", "off"}
    )
    projection_coefficients = None
    projection_update = None
    if full_workspace_projection and existing_columns:
        projection_coefficients = cp.empty(
            (workspace_columns, candidate.shape[1]),
            dtype=cp.float64,
            order="F",
        )
        if not fused_prefix_update:
            projection_update = cp.empty_like(candidate, order="F")

    def project_prefix(target: Any):
        if not existing_columns:
            return cp.empty((0, target.shape[1]), dtype=cp.float64)
        if not full_workspace_projection:
            coefficients = prefix.T @ target
            target -= prefix @ coefficients
            return coefficients
        cp.matmul(
            basis.T,
            target,
            out=projection_coefficients,
        )
        if fused_prefix_update:
            subtract_active_prefix(
                cp,
                basis,
                projection_coefficients,
                target,
                active_columns=existing_columns,
            )
        else:
            projection_coefficients[existing_columns:, :] = 0.0
            cp.matmul(
                basis,
                projection_coefficients,
                out=projection_update,
            )
            target -= projection_update
        return projection_coefficients[:existing_columns]

    second_prefix_coefficients = cp.empty(
        (0, candidate.shape[1]), dtype=cp.float64
    )
    if existing_columns:
        project_prefix(candidate)
        second_prefix_coefficients = project_prefix(candidate).copy()

    def audited(
        candidate_basis: Any,
        diagonal: np.ndarray,
        prefix_coefficients: Any,
    ) -> bool:
        internal = candidate_basis.T @ candidate_basis
        if prefix_coefficients.size:
            audit_values = cp.concatenate(
                (
                    internal.ravel(),
                    prefix_coefficients.ravel(),
                )
            )
        else:
            audit_values = internal.ravel()
        host = np.asarray(cp.asnumpy(audit_values), dtype=np.float64)
        block_count = columns - existing_columns
        gram_values = host[
            : block_count * block_count
        ].reshape(block_count, block_count)
        cross_values = host[block_count * block_count :]
        scale = max(float(np.max(np.abs(diagonal), initial=0.0)), 1.0)
        rank_ok = bool(
            np.isfinite(diagonal).all()
            and np.min(np.abs(diagonal), initial=np.inf)
            > np.finfo(np.float64).eps * max(rows, columns) * scale
        )
        internal_error = float(
            np.max(
                np.abs(gram_values - np.eye(block_count, dtype=np.float64)),
                initial=0.0,
            )
        )
        cross_error = float(
            np.max(np.abs(cross_values), initial=0.0)
        )
        return bool(
            rank_ok
            and np.isfinite(internal_error)
            and np.isfinite(cross_error)
            and internal_error <= 5.0e-11
            and cross_error <= 5.0e-11
        )

    try:
        first_norms = []
        for pass_number in range(2):
            for column in range(columns - existing_columns):
                vector = candidate[:, column]
                if column:
                    previous = candidate[:, :column]
                    vector = vector - previous @ (previous.T @ vector)
                norm = cp.linalg.norm(vector)
                if pass_number == 0:
                    first_norms.append(norm)
                safe_norm = cp.where(norm > 0.0, norm, 1.0)
                candidate[:, column] = vector / safe_norm
        audit_ok = audited(
            candidate,
            np.asarray(cp.asnumpy(cp.stack(first_norms)), dtype=np.float64),
            second_prefix_coefficients,
        )
    except Exception:
        audit_ok = False
    accepted_algorithm = "block_cgs2_device_mgs2"

    # The internal block has only six columns, so two synchronization-free
    # MGS passes are faster here than repeatedly starting tall cuSOLVER QR.
    # Householder QR remains a robust device fallback before the literal
    # replacement-capable PARSEC path is considered.
    if not audit_ok:
        accepted_algorithm = "block_cgs2_householder_qr"
        try:
            candidate = cp.asfortranarray(original)
            fallback_prefix_coefficients = cp.empty(
                (0, candidate.shape[1]), dtype=cp.float64
            )
            if existing_columns:
                project_prefix(candidate)
                fallback_prefix_coefficients = project_prefix(candidate).copy()
            candidate, triangular = cp.linalg.qr(candidate, mode="reduced")
            audit_ok = audited(
                candidate,
                np.asarray(cp.asnumpy(cp.diag(triangular)), dtype=np.float64),
                fallback_prefix_coefficients,
            )
        except Exception:
            audit_ok = False

    if audit_ok:
        appended[:, :] = candidate
        return DeviceOrthonormalizationResult(
            basis, 0, 0, algorithm=accepted_algorithm
        )

    appended[:, :] = original
    return _orthonormalize_literal(
        basis,
        existing_columns=existing_columns,
        existing_are_orthonormal=True,
        rng=rng,
        max_replacements=max_replacements,
        copy=False,
    )


def _complete_subspace_policy(row_count: int, column_count: int) -> str:
    """Select the complete-basis algorithm for the current problem size.

    PARSEC's selective MGS is fastest for its usual small representation
    sectors because it avoids a cuSOLVER setup and large QR workspace.  A
    full-grid molecular calculation can instead contain hundreds of
    thousands of rows and tens of states.  There the sequential level-2 BLAS
    projections in MGS dominate the SCF, while Householder QR performs the
    same span construction with GPU-efficient blocked level-3 operations.

    ``N * m**2`` is the shared leading work scale for orthogonalizing an
    ``N x m`` basis.  The deliberately conservative default threshold keeps
    all small-sector behavior unchanged and switches only when that work is
    large enough to amortize QR.  Explicit ``mgs``, ``qr``, and ``cholqr2``
    policies remain available for source tracing and architecture-specific
    profiling.
    """

    policy = os.environ.get(
        "PARSEC_CUPY_SUBSPACE_ORTHOGONALIZATION", "auto"
    ).strip().lower()
    # Compatibility with the earlier experimental boolean switch.
    legacy = os.environ.get("PARSEC_CUPY_SUBSPACE_QR")
    if legacy is not None:
        return (
            "qr"
            if legacy.strip().lower() not in {"0", "false", "no", "off"}
            else "mgs"
        )
    if policy not in {"auto", "mgs", "qr", "cholqr2"}:
        raise ValueError(
            "PARSEC_CUPY_SUBSPACE_ORTHOGONALIZATION must be auto, mgs, "
            "qr, or cholqr2"
        )
    if policy != "auto":
        return policy

    raw_threshold = os.environ.get(
        "PARSEC_CUPY_SUBSPACE_QR_WORK_THRESHOLD",
        str(_DEFAULT_QR_WORK_THRESHOLD),
    ).strip()
    try:
        threshold = int(raw_threshold)
    except ValueError as error:
        raise ValueError(
            "PARSEC_CUPY_SUBSPACE_QR_WORK_THRESHOLD must be an integer"
        ) from error
    if threshold < 0:
        raise ValueError(
            "PARSEC_CUPY_SUBSPACE_QR_WORK_THRESHOLD cannot be negative"
        )
    work = int(row_count) * int(column_count) * int(column_count)
    return "qr" if work >= threshold else "mgs"


def orthonormalize_complete_subspace(
    vectors: Any,
    *,
    rng: Any | None = None,
) -> DeviceOrthonormalizationResult:
    """Orthonormalize a complete filtered subspace with an adaptive method.

    Small representation sectors retain the audited PARSEC selective MGS
    implementation.  For sufficiently large full-grid bases, blocked
    Householder QR computes the same orthonormal span far more efficiently on
    a GPU and gives the following Rayleigh--Ritz products a favorable dense
    layout.  Set ``PARSEC_CUPY_SUBSPACE_ORTHOGONALIZATION`` to ``mgs``, ``qr``,
    or ``cholqr2`` to override the size-adaptive default.
    """

    cp, _ = require_cupy()
    matrix = cp.asarray(vectors, dtype=cp.float64)
    if matrix.ndim != 2 or matrix.shape[0] < matrix.shape[1]:
        raise ValueError("cannot construct the requested orthonormal subspace")
    policy = _complete_subspace_policy(*map(int, matrix.shape))
    if policy == "mgs":
        return orthonormalize(matrix, rng=rng)
    if policy == "qr":
        basis, _triangular = cp.linalg.qr(matrix, mode="reduced")
    else:
        # CholeskyQR2 reduces the many scalar synchronizations of selective
        # Gram--Schmidt to two small Gram transfers.  The second pass restores
        # near-machine orthogonality.  An ill-conditioned/indefinite Gram or
        # a failed accuracy audit falls back to PARSEC's robust MGS routine.
        basis = matrix
        try:
            for _ in range(2):
                gram = np.asarray(cp.asnumpy(basis.T @ basis), dtype=np.float64)
                gram = np.tril(gram) + np.tril(gram, -1).T
                cholesky = np.linalg.cholesky(gram)
                inverse_transpose = np.linalg.solve(
                    cholesky.T, np.eye(cholesky.shape[0], dtype=np.float64)
                )
                basis = basis @ cp.asarray(
                    inverse_transpose, dtype=cp.float64
                )
            audit = np.asarray(cp.asnumpy(basis.T @ basis), dtype=np.float64)
            error = float(
                np.max(
                    np.abs(audit - np.eye(audit.shape[0], dtype=np.float64)),
                    initial=0.0,
                )
            )
            if not np.isfinite(error) or error > 5.0e-11:
                raise np.linalg.LinAlgError(
                    f"CholeskyQR2 orthogonality audit failed ({error:.3e})"
                )
        except np.linalg.LinAlgError:
            return orthonormalize(matrix, rng=rng)
    return DeviceOrthonormalizationResult(
        basis=basis,
        random_replacements=0,
        zero_replacements=0,
    )


__all__ = [
    "DeviceOrthonormalizationResult",
    "chebdav_block_orth_requested",
    "orthonormalize",
    "orthonormalize_appended_block",
    "orthonormalize_complete_subspace",
]
