"""Hybrid policy for tiny dense eigensystems generated by GPU filters.

The real-space Hamiltonian action belongs on the GPU.  Its Rayleigh--Ritz and
Chebyshev--Davidson projections, however, are commonly only 7--30 square.
Launching a separate cuSOLVER ``syevd`` for each such matrix costs far more
than transferring a few kilobytes and using the process's optimized LAPACK.
This module keeps that scale decision explicit and reversible.
"""

from __future__ import annotations

import os
from typing import Any

import numpy as np

from ..backends.cupy import require_cupy


def _host_threshold() -> int:
    raw = os.environ.get("PARSEC_CUPY_HOST_EIGH_MAX", "64").strip()
    try:
        value = int(raw)
    except ValueError as error:
        raise ValueError("PARSEC_CUPY_HOST_EIGH_MAX must be an integer") from error
    if value < 0:
        raise ValueError("PARSEC_CUPY_HOST_EIGH_MAX cannot be negative")
    return value


def symmetric_eigh(
    matrix: Any,
    *,
    return_host_values: bool = False,
):
    """Diagonalize a symmetric device matrix on the best size regime.

    A threshold of zero restores the original all-GPU behavior.  Both paths
    return CuPy arrays, so every subsequent grid-by-subspace rotation remains
    device resident.  NumPy and CuPy both call double-precision symmetric
    LAPACK/cuSOLVER routines; this changes execution placement, not the
    projected eigenproblem or its requested precision.
    """

    cp, _ = require_cupy()
    device = cp.asarray(matrix, dtype=cp.float64)
    if device.ndim != 2 or device.shape[0] != device.shape[1]:
        raise ValueError("symmetric_eigh requires one square matrix")
    if int(device.shape[0]) > _host_threshold():
        device_values, device_vectors = cp.linalg.eigh(device)
        if return_host_values:
            host_values = np.asarray(
                cp.asnumpy(device_values), dtype=np.float64
            )
            return device_values, device_vectors, host_values
        return device_values, device_vectors
    host_values, host_vectors = np.linalg.eigh(
        np.asarray(cp.asnumpy(device), dtype=np.float64)
    )
    device_result = (
        cp.asarray(host_values, dtype=cp.float64),
        cp.asarray(host_vectors, dtype=cp.float64),
    )
    if return_host_values:
        # CHEBDAV immediately needs several Ritz values for scalar convergence
        # and filter-window decisions.  Reuse the LAPACK result already on the
        # host instead of synchronizing the CUDA stream for each scalar.
        return (*device_result, host_values)
    return device_result


__all__ = ["symmetric_eigh"]
